site_name: Common Fund Data Ecosystem Training

repo_url: https://github.com/nih-cfde/training-and-engagement

theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs
    - navigation.instant
  logo: images/CFDE-logo.png
  custom_dir: docs/templates
docs_dir: docs

plugins:
  - search: # necessary for search to work
      separator: '[\s\-\.]+'
  - awesome-pages
  - git-revision-date-localized
  - htmlproofer

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.emoji
- pymdownx.extra
- codehilite:
    guess_lang: false
- toc:
    permalink: true
extra:
  hypothesis: true
extra_css:
  - stylesheets/extra.css
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/medium-zoom.min.js
  - javascripts/extra.js
  - javascripts/asciinema-player.js
