name: 'Auto Assign'
on:
  # Trigger the workflow on pull request,
  # but only for the latest branch
  pull_request:
    branches:
      - stable

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          repo-token: ${{ secrets.ALLTHEACTIONS }}
          configuration-path: ".github/actions/auto_assign_stable.yml"
